### PR TITLE
Respect user's target low and target high

### LINKED ISSUE #318: Respect connection's target low and target high instead of 70-180 default
### :warning: Is your feature request related to a problem? Please describe.

I was reading the code and I came across [this](https://github.com/Crazy-Marvin/LibreLinkUpDesktop/blob/development/src/renderer/pages/dashboard.tsx#L35-L41):
```tsx
  const getColor = (value: number): string => {
    if (value > 70 && value < 180) {
      return "bg-green-500"
    }

    return "bg-yellow-500"
  }
```
this means values in range of 70-180 will be green and the rest will be yellow. But me personally, I want green for 80-160 range and I have applied this in my LibreLink app settings.

### :bulb: Describe the solution you'd like.

According to [this HTTP dump](https://gist.github.com/khskekec/6c13ba01b10d3018d816706a32ae8ab2) the `data.connection` object includes `targetLow` and `targetHigh`.

### :raising_hand: Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by dakyskye**
This fixes #318

Obviously I am no JavaScript/React etc. master but I think this is a fine implementation. Of course it needed to be tested if the colours would actually change. This is what I did in order to test 😅
```ts
var horrible = 0;
```
globally in `dashboard.tsx` and I modified `getColor` func body to begin with:
```ts
    if (horrible === 0) {
      value = 169;
      horrible = 1;
    } else if (horrible === 1) {
      value = 45;
      horrible = 2;
    } else if (horrible === 2) {
      value = 79;
      horrible = 3;
    } else if (horrible === 3) {
      value = 130;
      horrible = 4;
    } else if (horrible === 4) {
      value = 235;
      horrible = 5;
    } else if (horrible ===5 ) {
      value = 300;
      horrible = -1;
    }
```
in my case `targetLow` was `80` and `targetHigh` was `160`. Everything happened as exepcted. First it turned yellow, then red, then yellow, then green, then yellow, then orange.

### CODE REVIEW

**Comment by dakyskye** [comment]
Right now:
image

And I am happy to see this in yellow. Because that's how I see it on my smartphone.

**Comment by CrazyMarvin** [comment]
Awesome, thanks @dakyskye!
What do you think about it, @fperera123?

**Comment by dakyskye** [comment]
Hey @CrazyMarvin , @fperera123 ; what do you think?

**Comment by fperera123** [comment]
This is great and it is working as follows;

- Red: value < LOW
- Orange: value > HIGH
- Yellow: (value < userSetTargetLow && value >= LOW) || (value > userSetTargetHigh && value <= HIGH)
- Green: otherwise

@CrazyMarvin We can put this in the next release.

**Comment by CrazyMarvin** [comment]
> This is great and it is working as follows;
> 
> - Red: value < LOW
> - Orange: value > HIGH
> - Yellow: (value < userSetTargetLow && value >= LOW) || (value > userSetTargetHigh && value <= HIGH)
> - Green: otherwise
> 
> @CrazyMarvin We can put this in the next release. 
> 

Thanks for checking. I will merge it now.

**Pull request merged**
