### PR TITLE
Corrected the up/down trend icons

### PR DESCRIPTION
**Pull request by robsonjb1**
I believe the up and down icons are the wrong way around (ie upward trend is showing with down arrow).
 
Also added the additional top right and bottom right icons as well.

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
Thank you very much for your PR, @robsonjb1. 👍

I am not really sure about the arrow directions. I will have a closer look.

What do you think about the PR, @fperera123?

**Comment by robsonjb1** [comment]
I tested this with my Libre 2 (and some chocolate!). 

I think the TrendArrow value returned from the API (numeric 1 to 5) goes low to high (rather than high to low).
1 = very low
2 = gradual low
3 = steady
4 = gradual high
5 = high

**Comment by CrazyMarvin** [comment]
> I tested this with my Libre 2 (and some chocolate!).
> 
> I think the TrendArrow value returned from the API (numeric 1 to 5) goes low to high (rather than high to low). 1 = very low 2 = gradual low 3 = steady 4 = gradual high 5 = high

You are right.

            1 => ⬇️
            2 => ↘️
            3 => ➡️
            4 => ↗️
            5 => ⬆️

Merge should be fine, shouldn't it @fperera123?

**Comment by fperera123** [comment]
Yes this is fine

**Pull request merged**
